apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: webapp1
        image: 572392880480.dkr.ecr.us-east-1.amazonaws.com/webapp1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp1
    k8s-app: webapp1
  name: webapp1
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: webapp1
